### ISSUE TITLE
Upload error on era-test

### ISSUE THREAD

**Issue by piyapongch** [ualbertalib/HydraNorth#217]
I have got an error message, Error occurred while creating generic file. when I tried to upload pdf to era-test.

**Comment by pgwillia** [comment]
```
GenericFilesController::create rescued MiniMagick::Invalid
        `gm identify /tmp/mini_magick20150423-9064-6fkm8e` failed with error:
execvp failed, errno = 2 (No such file or directory)
gm identify: "gs" "-q" "-dBATCH" "-dMaxBitmap=50000000" "-dNOPAUSE" "-sDEVICE=ppmraw" "-dTextAlphaBits=4" "-dGraphicsAlphaBits=4" "-r72x72" "-sOutputFile=/tmp/gmpiRhD3" "--" "/tmp/gmeAP0mw" "-c" "quit".
gm identify: Postscript delegate failed (/tmp/mini_magick20150423-9064-6fkm8e).
gm identify: Request did not return an image.
```

**Comment by pgwillia** [comment]
Ghostscript is missing from the test server
```
[pjenkins@oldham hydranorth]$ gs
-bash: gs: command not found
```

**Comment by pgwillia** [comment]
@henryzhang87 these packages are required on all servers:
```
  - name: Install prerequisite software
    yum: pkg={{ item}} state=latest
    with_items:
      - ruby
      - ImageMagick-devel
#      - ualib-rails # for bundler
      - clamd
      - nodejs
      - poppler-utils
      - libreoffice-headless
      - libreoffice
      - GraphicsMagick
```

I'll see why ImageMagick-devel is required -- I remember this being a conscious decision.
